### ISSUE TITLE
BUG: Players can use blacklisted items when they store them in their backpack.

### ISSUE THREAD

**Issue by Freddy555ch** [Wyqer/kp_liberation#279] opened 2017-11-27 13:25 UTC
### Basic Information
**Mission version:**
 0.961
**Map used:**
 Altis and Tanoa
**Mods used:**
Advanced Sling Loading, Advanced Towing, CBA_A3, Enhanced Movement, Enhanced Visuals, FEMAL3 Heads, FEMAL3 Uniforms, Immerse, JSRS Soundmod, JSRS Soundmod - Addtional weapon handling and reloading Sounds, Suppress, Sweet Markers Systems , Task Force Radio, WMO - Walkable Moving Objects
**Dedicated or local game?**
Dedicated
**GitHub or Workshop mission file?**
Workshop
### Individual Things
**Did you edit anything within the mission files?**
Yes

**If yes, what did you edit exactly?**
Only Params

### Short Issue Description
If you load a pre created set from the Arsenal with blacklisted items **inside** your Backpack, you can leave the arsenal without any problems and use the Items. Example: Nightstalker Vision

### Expected Behaviour
The item should've been removed or the set locked.

### Steps to Reproduce the Issue

1. Create and save a virtual arsenal set with a backpack and an restricted item. (for example the Nightstalker Vision)
2. Remove the vision from your weapon, pack in inside your backpack and save the set again.
3. Load the set while playing the mission.
4. Now you can remove the vision from the backpack and use it on the weapon.

**Comment by Wyqer** [comment] 2017-11-27 14:42
Tested it now and I can't confirm this behaviour for the "virtual arsenal" in the mission. I've done your reproduce steps and after loading it from the arsenal, then leaving the arsenal it was found in my backpack and I lost my gear. So as expected and intended.

What I can reproduce is, that it isn't found after just loading the loadout from the liberation arsenal ui (Before you can enter the "real arsenal").

Will have a look at it.

**Comment by Wyqer** [comment] 2017-11-27 14:52
Already fixed in the upcoming version.
It was a kind of typo in the actual file:
https://github.com/Wyqer/kp_liberation/blob/master/Missionframework/scripts/client/actions/open_arsenal.sqf#L83

If you scroll further down you see that the above check is missing this line:

    {if ((_x != "") && !(_x in _playerItems)) then {_playerItems pushback _x;};} forEach (backpackItems player);

That's why direct loading worked.

But as I already put these checks in a function to remove redundancy it's already fixed in the next version.

Thanks for report. It must have been there since 0.94 I guess ^^

**Closed** 2017-11-28 05:38 UTC
Labels: BUG, Finished
