### ISSUE TITLE
Slingloading of Resources

### ISSUE THREAD

**Issue by Vastiny** [Wyqer/kp_liberation#94] opened 2017-05-23 15:10 UTC
When attempting to Slingload a Resource crate that has previously been Loaded into a vehicle OR Stored into a Storage area, it will no longer register on the Slingload Assistant and you won't be able to hook it to a helicopter!

**Comment by Wyqer** [comment] 2017-05-23 15:36
If I don't missunderstand, that's intended behaviour. You can't slingload crates which are actually loaded on a truck or stored in a area. You've to unstore or unload it before.

The function to load or store does this on the crate:
`[the crate] enableRopeAttach false;`
The function to unload or unstore does:
`[the crate] enableRopeAttach true;`

referring:
https://community.bistudio.com/wiki/enableRopeAttach

**Comment by Vastiny** [comment] 2017-05-23 15:46
I think I worded the issue a bit strangely, what I mean is once you first approach the crates (while they're not loaded or stored or anything) they're able to be Slingloaded, however once you've loaded or stored them atleast once into any container, and then unload them, you can no longer Slingload them

**Comment by Wyqer** [comment] 2017-05-23 16:15
One comment about the function say, that you may have to close and reopen the assistant once.
So unloading/unstore and then close/reopen the assistant may solve it.
But I'll have a look at it. Maybe it's something with the locality of the crate object in MP.
Too bad, that the wiki don't point if the effect is local or global.

**Comment by Xterm** [comment] 2017-05-25 19:58
I have the same issue. Sadly closing and reopening the assistant did not help :-(

However, playing on Chernarus there are civilian trucks that can carry crates and after having loaded the crates into one of these truck and then dumped the crates, the crates were showing up on the sling load assistant again.

**Comment by Wyqer** [comment] 2017-05-25 20:07
Ok.....
Do you play on local hosted MP or on a dedicated server?
Alone or with friends?
And if you loaded the crate on a vehicle and unloaded it, it will show again in the assistant?

Could you maybe test something?
1. Get a crate which you can see in the assistant.
2. Fly the crate to your storage area and. You load it inside the area, wait some seconds and unload it again. Do you still see it in the assistant and maybe your friends not?
3. Let one of your friends now store and unstore it from the area.
Can you still see it in the assistant or can maybe your "loading" friend now see it in the assistant?
4. Do steps 2 and 3 also with a truck and check the behaviour of the assistant.

That would help me investigating the behaviour of the command in MP with different localities.
Thanks in advance.

**Comment by Xterm** [comment] 2017-05-25 21:44
This is playing with friends on a dedicated server.

Will see if I can get them to jump into a helicopter and test it out.

**Comment by Wyqer** [comment] 2017-05-26 04:54
Please use also the following files (keep an Backup of the old ones) for the tests and hand me over the server.rpt
That would be really helpful to find some hints for the cause of this issue.
[ropeAttachDebug.zip](https://github.com/Wyqer/kp_liberation/files/1030842/ropeAttachDebug.zip)

**Closed** 2017-06-05 06:28 UTC
Labels: BUG, Finished
